models.py
from app import db

roles_users = db.Table('roles_users', 
	                   db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
	                   db.Column('role_id', db.Integer(), db.ForeignKey('role.id')),
	                   extend_existing=True)

users_texts = db.Table('users_texts',
                     db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                     db.Column('text_id', db.Integer, db.ForeignKey('text.id')),
                     extend_existing=True)

class User(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(100))
	surname = db.Column(db.String(100))
	email = db.Column(db.String(100), unique = True)
	password = db.Column(db.String(100))

	texts = db.relationship('Text', secondary = users_texts, backref = db.backref('users', lazy = 'dynamic'))


	roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(100), unique=True)
	description = db.Column(db.String(255))	


class Text(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	text = db.Column(db.Text)
	name = db.Column(db.String(140))

Txt/forms.py
from wtforms import Form, StringField, TextAreaField
class EditTextForm(Form):
	name = StringField('name')
	text = TextAreaField('text')

forms.py
from wtforms import Form, StringField

class RegisterForm(Form):
	name = StringField('name')
	surname = StringField('surname')
	email = StringField('email')
	password = StringField('password')

Txt/blueprint.py
from flask import Blueprint
from flask import render_template
from models import User, Text
from Txt.forms import EditTextForm
from flask import request
from app import db

txt = Blueprint('Txt', __name__, template_folder='templates', static_folder='static')

@txt.route('/User-<email>')
def txt_main(email):
    user = User.query.filter(User.email==email).first()
    print(user) 
    texts = user.texts
    return render_template('texts.html', texts = texts)

@txt.route('/Text-<id>', methods = ['POST', 'GET'])
def text(id):
    t_object = Text.query.filter(Text.id==id).first()
    if request.method == 'POST':
        form = EditTextForm(formdata = request.form, obj = t_object)
        form.populate_obj(t_object)
        db.session.commit()
    form = EditTextForm(obj=t_object)
    name = form.name
    text = form.text
    return render_template('edit_text.html', form = form, t_object = t_object, text = text, name = name)

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager


app = Flask(__name__)
app.config.from_object(Configuration)
db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

#from models import *
#user_datastore = SQLAlchemyUserDatastore(db, User, Role)

#security = Security(app, user_datastore)

main.py
from app import app
import view
from Txt.blueprint import txt

app.register_blueprint(txt, url_prefix = '/Txt')

if __name__ == '__main__':
	app.run()

Txt/templates/edit_text.html
<!DOCTYPE html>

<html>
 <head>
  <link href="static/edit_text.css", rel="stylesheet", text="text/css"/>
 </head>

 <body>
  <p class="logo">DocsHub®</p>
  <form action="{{ url_for('Txt.text', id = t_object.id) }}", method="POST">
   {{ name(class="input") }}
   {{ text(class="edit") }}
   <button class="submit", type="submit">SAVE>></button>
  </form>
 </body>

</html>

Txt/templates/texts.html
<!DOCTYPE html>
<html/>

 <head>
  <link href="static/text.css", rel="stylesheet", text="text/css"/>
 </head>

 <body>
  <p class="main">DocsHub</p>
  {% for text in texts %}
   <form action="{{ url_for('Txt.text', id = text.id) }}">
    <p class="docs">{{ text.name }}</p><button type="Submit">OPEN</button>
   </form>
  {% endfor %}
 </body>

</html>

templates/docs.html
<!DOCTYPE html>

<html>
 <head>
  <link href="static/docs.css", rel="stylesheet", text="text/css"/>
  <meta charset="UTF-8" />
  <title>{{ name }}</title>
 </head>

 <body>
  <p class="p">DocsHub®</p>

  <form action="http://google.com"><button class="img"><p class="marg">Images<p/></button></form>
  <form action="{{ url_for('Txt.txt_main', email = email) }}"><button class="txt"><p class="marg">TXT<p/></button></form>
  <form action="http://google.com"><button class="mus"><p class="marg">Music<p/></button></form>
  <form action="http://google.com"><button class="code"><p class="marg">Code<p/></button></form>
 </body>

</html>

templates/log.html
<!DOCTYPE html>

<html>
 <head>
  <link href="static/log.css", rel="stylesheet", text="text/css"/>
  <meta charset="UTF-8" />
 </head>

 <body>
  <p>DocsHub®</p>
  <div class="main">
   <form class="send", action="{{ url_for('login') }}", method="POST">  
    {{ email(placeholder="Your Email", class="email", autocomplete="off") }}
    {{ password(placeholder="Your password", class="password", autocomplete="off") }}
    <button type="submit">Enter</button>
   </form>
   <text>{{ error }}</text>
  </div>
 </body>

</html>

templates/main.html
<!DOCTYPE html>
<html/>

 <head>
  <link href="static/main.css", rel="stylesheet", text="text/css"/>
 </head>

 <body>
  <a href="/register"><div class="log">Register</div></a>
  <a href="/login"><div class="reg">Docs</div></a>
  <p class="main">DocsHub</p>
 </body>

</html>

templates/reg.html
<!DOCTYPE html>

<html>
 <head>
  <link href="static/reg.css", rel="stylesheet", text="text/css"/>
  <meta charset="UTF-8" />
 </head>

 <body>
  <p>DocsHub®</p>
  <div class="main">
   <form class="send", action="{{ url_for('register') }}", method="POST">  
    {{ name(placeholder="Your name", class="name", autocomplete="off") }}
    {{ surname(placeholder="Your surname", class="surname", autocomplete="off") }}
    {{ email(placeholder="Your Email", class="email", autocomplete="off") }}
    {{ password(placeholder="Your password", class="password", autocomplete="off") }}
    <button type="submit">Enter</button>
   </form>
   <text>{{ error }}</text>
  </div>
 </body>

</html>